### ISSUE TITLE
MOAR examples

### ISSUE THREAD

**Issue by dAnjou** [ikotler/pythonect#2]
The "Hello World" does not show anything ;P

**Comment by ikotler** [comment]
Not quite sure what you meant there, but if you are looking for more examples see: https://github.com/ikotler/pythonect/wiki/Pythonect-Tutorial:-Learn-By-Example

**Comment by dAnjou** [comment]
You posted an announcement on reddit some time ago. I went here and the documentation was almost naked. Now I see that you have a lot of examples which is exactly what I was looking for ;)

**Comment by ikotler** [comment]
Happy to hear. If you have any questions or comments please send a message to the mailing list.
