### ISSUE TITLE
accidentally reverted wiki page ... sorry

### ISSUE THREAD

**Issue by mattfenwick** [ikotler/pythonect#24]
Hi ... this is an embarrassing issue, but I accidentally clicked revert when I was looking at your wiki ([here](https://github.com/ikotler/pythonect/wiki/Roadmap/_history)) and I can't figure out how to undo it.

I'm really sorry for causing you more work!

**Comment by mattfenwick** [comment]
Okay, I think I may have fixed it by reverting the revert.  Did that do it?

Once again, I want to apologize for this.

**Comment by ikotler** [comment]
Hi Matt,

No worries, the revert you did fixed it.

Did you want to add anything to the Roadmap?

**Comment by mattfenwick** [comment]
No, I just clicked on the wrong spot.
