### ISSUE TITLE
Linear growth of termination time

### ISSUE THREAD

**Issue by TLbugs** [ikotler/pythonect#50]
For some reason, **_after**_ iterating through a list, pythonect hangs for an amount of time that correlates with the number of iterations that have been done.
Benchmarks performed on a 2.2GHz Core2Duo Windows 7 machine.

`[[range(1)]] -> [sys.stdout.write(str(x)) for x in _[0]]` (2.2816 seconds)
`[[range(2)]] -> [sys.stdout.write(str(x)) for x in _[0]]` (3.2782 seconds)
`[[range(3)]] -> [sys.stdout.write(str(x)) for x in _[0]]` (4.3306 seconds)
`[[range(4)]] -> [sys.stdout.write(str(x)) for x in _[0]]` (5.2891 seconds)
`[[range(5)]] -> [sys.stdout.write(str(x)) for x in _[0]]` (6.3092 seconds)
`[[range(100)]] -> [sys.stdout.write(str(x)) for x in _[0]]` (101.3167 seconds)

**Comment by ikotler** [comment]
Hangs after you see the prompt, or before? eval() is synchronous and won't give control back to the interpreter unless all threads are join()'ed.
