### ISSUE TITLE
Exception from documentation

### ISSUE THREAD

**Issue by jkbbwr** [ikotler/pythonect#74]
> > > "Hello, world" -> print &
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python2.7/dist-packages/pythonect/internal/eval.py", line 836, in eval
> > >     result = **run(expressions[0], globals_, locals_, None)
> > >   File "/usr/local/lib/python2.7/dist-packages/pythonect/internal/eval.py", line 611, in __run
> > >     (expression, provider) = __change_provider_in_single(expression, operator, globals_, locals_)
> > >   File "/usr/local/lib/python2.7/dist-packages/pythonect/internal/eval.py", line 576, in __change_provider_in_single
> > >     return (expression, __create_pool(globals_, locals_))
> > >   File "/usr/local/lib/python2.7/dist-packages/pythonect/internal/eval.py", line 119, in __create_pool
> > >     return NoDaemonPool(locals_.get('__MAX_PROCESSES_PER_FLOW**', None))
> > >   File "/usr/lib/python2.7/multiprocessing/pool.py", line 115, in **init**
> > >     self._setup_queues()
> > >   File "/usr/lib/python2.7/multiprocessing/pool.py", line 208, in _setup_queues
> > >     self._inqueue = SimpleQueue()
> > >   File "/usr/lib/python2.7/multiprocessing/queues.py", line 354, in __init__
> > >     self._rlock = Lock()
> > >   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
> > >     SemLock.**init**(self, SEMAPHORE, 1, 1)
> > >   File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in **init**
> > >     sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
> > > OSError: [Errno 38] Function not implemented

**Comment by ikotler** [comment]
The problem seems to be in Python, not Pythonect. Can you please share what OS/Platform/Python version are you using?

**Comment by jkbbwr** [comment]
Linux ve.vs67z7sn.vesrv.com 2.6.18-028stab101.1 #1 SMP Sun Jun 24 19:50:48 MSD 2 012 x86_64 x86_64 x86_64 GNU/Linux (ubuntu 11 I think)

jakob@ve:~$ python --version
Python 2.7.1+
